apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-server
  template:
    metadata:
      labels:
        app: gateway-server
    spec:
      containers:
      - name: gateway-server
        image: gateway-server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 5
      initContainers:
      - name: wait-for-dependencies
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z eureka-server 8761; do sleep 2; done']
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-server
  namespace: microservices
spec:
  selector:
    app: gateway-server
  ports:
  - port: 8080
    targetPort: 8080
  type: NodePort