FROM ghcr.io/graalvm/native-image-community:21 AS builder
WORKDIR /app
COPY . .
RUN chmod +x mvnw
RUN ./mvnw -Pnative native:compile -pl user-service -DskipTests

FROM ubuntu:noble
WORKDIR /app
COPY --from=builder /app/user-service/target/user-service .
EXPOSE 8081
ENTRYPOINT ["/app/user-service"]
